apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  labels:
    app: sentiment
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment
      type: api
  template:
    metadata:
      labels:
        app: sentiment
        type: api
    spec:
      containers:
        - name: sentiment-content-api
          image: quartercog/sentiment-content-api
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3001
          env:
            - name: DB_URL
              value: "ds213513.mlab.com:13513"
            - name: DB_NAME
              value: "sentiment-prod-test"
            - name: DB_CONTENT_API_USERNAME
              value: "content-api"
            - name: DB_CONTENT_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sentiment-secrets
                  key: db_content_api_password
            - name: DB_COLLECTION_NAME
              value: "articles"
