apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  labels:
    app: sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment
  template:
    metadata:
      labels:
        app: sentiment
    spec:
      containers:
        - name: content-api
          image: sentiment-content-api
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3001
